# Use uma imagem base com Dart 3.5.1 e prepare para instalar Flutter
FROM dart:3.5.1 AS base

# Instale as dependências necessárias, incluindo o protobuf-compiler e git
RUN apt-get update && apt-get install -y \
    unzip xz-utils zip libglu1-mesa git curl protobuf-compiler \
    clang cmake ninja-build pkg-config

# Instale o plugin protoc_plugin globalmente
RUN dart pub global activate protoc_plugin

# Clone o Flutter na versão 3.24.1 do canal stable
RUN git clone https://github.com/flutter/flutter.git -b stable --depth 1 /flutter

# Configure o Flutter SDK e Dart no PATH
ENV PATH="/flutter/bin:/flutter/bin/cache/dart-sdk/bin:/root/.pub-cache/bin:$PATH"
ENV FLUTTER_ROOT="/flutter"

# Mude para o canal stable, atualize o Flutter e verifique a instalação
RUN flutter channel stable
RUN flutter upgrade
RUN flutter doctor -v

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos necessários para instalar as dependências
COPY pubspec.* ./

# Limpe o cache de pacotes do Dart para evitar problemas
RUN flutter pub cache clean

# Instale as dependências do Flutter e do Dart
RUN flutter pub get --verbose

# Copie o restante dos arquivos do projeto
COPY . .

# Gere os arquivos Dart a partir dos arquivos .proto
RUN protoc --dart_out=grpc:lib -Ipb proto/*.proto --proto_path .

# Verifique se as dependências foram instaladas corretamente
RUN dart pub deps

# Imagem final usando uma base leve
FROM debian:buster-slim AS runtime

# Instale dependências mínimas para rodar a aplicação Dart, incluindo o git
RUN apt-get update && apt-get install -y \
    ca-certificates git curl libglu1-mesa clang cmake ninja-build pkg-config \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos do projeto e o Dart SDK da imagem base
COPY --from=base /app /app
COPY --from=base /usr/lib/dart /usr/lib/dart
COPY --from=base /flutter /flutter
COPY --from=base /root/.pub-cache /root/.pub-cache

# Configure o PATH para Dart e Flutter
ENV PATH="/usr/lib/dart/bin:/flutter/bin:/flutter/bin/cache/dart-sdk/bin:/root/.pub-cache/bin:$PATH"

# Exponha a porta que o servidor vai usar
EXPOSE 3002

# Comando para rodar a aplicação Dart
CMD ["dart", "run", "lib/main_backend.dart"]


# docker build -t dart-gzip-protobuf .
# docker run -p 3002:3002 dart-gzip-protobuf